### ISSUE TITLE
External port crash in rabbit_mgmt_external_stats:init/1 can affect other processes

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-management-agent#12]
See [this report](https://groups.google.com/forum/#!topic/rabbitmq-users/Sbv29klbVLE). This is the same issue as in https://github.com/rabbitmq/rabbitmq-server/issues/91, except in a different module.

The process should not stop in `init/1`, in fact, it should not attempt to retrieve the stats there, waiting for a moment is perfectly fine.

**Comment by michaelklishin** [comment]
Re-assigning to @hairyhum per discussion with him. Thank you for taking over.

**Comment by hairyhum** [comment]
`rabbit_mgmt_external_stats` is not emiting any stats in `init/1`, it sends itself message to emit later. So it's not the same issue. Needs more investigation on impact.

**Comment by michaelklishin** [comment]
A lot of things have changed since https://github.com/rabbitmq/rabbitmq-management/issues/236, so let's assume this is no longer relevant and see what long running test environments plus user feedback reveal.
