### ISSUE TITLE
rabbitmq-management-agent could prevent RabbitMQ to start

### ISSUE THREAD

**Issue by videlalvaro** [rabbitmq/rabbitmq-management-agent#4]
See this thread: https://groups.google.com/forum/#!topic/rabbitmq-users/HKMIwURSW4c

Relevant line: https://github.com/rabbitmq/rabbitmq-management-agent/blob/master/src/rabbit_mgmt_db_handler.erl#L64

RabbitMQ misc returns the `Val`, not `{ok, Val}`

**Comment by michaelklishin** [comment]
Fixed by #6.

**Comment by dumbbell** [comment]
Since RabbitMQ 3.5.2.
