### ISSUE TITLE
Sample retention policies init failure with 3.6.9

### ISSUE THREAD

**Issue by laurentluce** [rabbitmq/rabbitmq-management-agent#41]
This error seems to be linked to the sample retention policies initialization:

Config:

> {sample_retention_policies,
>     [{global,   [{60, 5}, {3600, 60}]},
>      {basic,    [{60, 20}, {3600, 360}]},
>      {detailed, [{10, 5}]}]}
>   ]},
> 

Error in log:

> "Error: {could_not_start,rabbitmq_management_agent,\n        {{shutdown,\n          {failed_to_start_child,rabbit_mgmt_agent_sup,\n           {shutdown,\n            {failed_to_start_child,\n             channel_queue_exchange_metrics_metrics_collector,\n             {function_clause,\n              [{lists,min,[[]],[{file,\"lists.erl\"},{line,315}]},\n               {rabbit_mgmt_metrics_collector,init,1,\n                [{file,\"src/rabbit_mgmt_metrics_collector.erl\"},{line,73}]},\n               {gen_server,init_it,6,[{file,\"gen_server.erl\"},{line,328}]},\n               {proc_lib,init_p_do_apply,3,\n                [{file,\"proc_lib.erl\"},{line,247}]}]}}}}},\n         {rabbit_mgmt_agent_app,start,[normal,[]]}}}"

It used to work with 3.6.6.

**Comment by kjnilsson** [comment]
hi @laurentluce - I've tried your config but am not able to reproduce it. Could you paste a more complete config file I could try?

**Comment by laurentluce** [comment]
Full config:

```
[
 {rabbit,
   {vm_memory_high_watermark, 0.75},
   {vm_memory_high_watermark_paging_ratio, 0.9},
   {cluster_partition_handling, autoheal},
   {collect_statistics_interval, 60000}
  ]},
 {mnesia, [{dump_log_write_threshold, 256}]},
  {autocluster,
  [
      {backend, aws},
      {aws_autoscaling, true},
      {autocluster_log_level, info},
      {autocluster_failure, ignore},
      {cluster_cleanup, true},
      {cleanup_warn_only, false}
  ]},
 {kernel,
  ]},
 {rabbitmq_management,
   {listener, [{port,     15672},
                {ssl,      false},
                {ssl_opts, [{cacertfile, "/etc/rabbitmq/ssl/cacert.pem"},
                            {certfile,   "/etc/rabbitmq/ssl/server.pem"},
                            {keyfile,    "/etc/rabbitmq/ssl/server.key"}]}]},
   {rates_mode, none},
   {sample_retention_policies,
    [{global, [{60, 5}, {3600, 60}]},
     {basic, [{60, 20}, {3600, 360}]},
     {detailed, [{10, 5}]}]}
  ]},
   {rabbitmq_web_stomp,
     {use_http_auth, true},
     {port, 15671},
     {ssl_config, [{port,     15674},
                   {backlog,    1024},
                   {recbuf, 32768},
                   {sndbuf, 32768},
                   {cacertfile, "/etc/rabbitmq/ssl/cacert.pem"},
                   {certfile,   "/etc/rabbitmq/ssl/server.pem"},
                   {keyfile,    "/etc/rabbitmq/ssl/server.key"}]}
    ]},
 {rabbitmq_shovel,
  [{shovels,
    ]}
  ]},
 {rabbitmq_stomp,
  ]},
 {rabbitmq_mqtt,
  ]},
 {rabbitmq_amqp1_0,
  ]},
 {rabbitmq_auth_backend_ldap,
  ]},
  {lager, [
  ]}
].
```

**Comment by laurentluce** [comment]
If I change the sample retention policies to the following, it works fine:

```
{sample_retention_policies,
    [{global,   [{60, 5}]},
     {basic,    [{60, 20}]},
     {detailed, [{10, 5}]}]}
  ]},
```

**Comment by kjnilsson** [comment]
I don't understand how your full config works at all, it is full of syntax errors. I tested it after correcting them and still cannot reproduce. Do the errors occur straight away after boot or do you have to take any particular steps to make them happen?

Please can you try the corrected config below:

```
[
 {rabbit, [
   {vm_memory_high_watermark, 0.75},
   {vm_memory_high_watermark_paging_ratio, 0.9},
   {cluster_partition_handling, autoheal},
   {collect_statistics_interval, 60000}
  ]},
 {mnesia, [{dump_log_write_threshold, 256}]},
  {autocluster,
  [
      {backend, aws},
      {aws_autoscaling, true},
      {autocluster_log_level, info},
      {autocluster_failure, ignore},
      {cluster_cleanup, true},
      {cleanup_warn_only, false}
  ]},
 {kernel, [
  ]},
 {rabbitmq_management, [
   {listener, [{port,     15672},
                {ssl,      false},
                {ssl_opts, [{cacertfile, "/etc/rabbitmq/ssl/cacert.pem"},
                            {certfile,   "/etc/rabbitmq/ssl/server.pem"},
                            {keyfile,    "/etc/rabbitmq/ssl/server.key"}]}]},
   {rates_mode, none},
   {sample_retention_policies,
    [{global, [{60, 5}, {3600, 60}]},
     {basic, [{60, 20}, {3600, 360}]},
     {detailed, [{10, 5}]}]}
  ]},
   {rabbitmq_web_stomp, [
     {use_http_auth, true},
     {port, 15671},
     {ssl_config, [{port,     15674},
                   {backlog,    1024},
                   {recbuf, 32768},
                   {sndbuf, 32768},
                   {cacertfile, "/etc/rabbitmq/ssl/cacert.pem"},
                   {certfile,   "/etc/rabbitmq/ssl/server.pem"},
                   {keyfile,    "/etc/rabbitmq/ssl/server.key"}]}
    ]},
 {rabbitmq_shovel,
  [{shovels, [
    ]}
  ]},
 {rabbitmq_stomp, [
  ]},
 {rabbitmq_mqtt, [
  ]},
 {rabbitmq_amqp1_0, [
  ]},
 {rabbitmq_auth_backend_ldap, [
  ]},
  {lager, [
  ]}
].
```

**Comment by laurentluce** [comment]
Sorry about the format.  I used grep to remove the comments and something went wrong.

**Comment by laurentluce** [comment]
@kjnilsson  It happens for me during the initial startup on a brand new VM when the management plugin is enabled.  If I have a working setup and I start messing with the sample retention policies, it usually does not happen.

**Comment by laurentluce** [comment]
Since I am not able to reproduce this issue consistently and that I found some working configurations, I am closing it for now.

**Comment by michaelklishin** [comment]
It could be a race condition. We will see if we can reproduce. @dcorbacho might have a better insight than the rest of us here.

**Comment by dcorbacho** [comment]
I wonder if @laurentluce has retention policies configured both for `rabbitmq_management` and `rabbitmq_management_agent`, and occasionally `rabbitmq_management` is not yet loaded and we end up picking up a bad value from the agent (for the `detailed` stats in this case). It could be an empty list or a list that is not a proplist.

**Comment by laurentluce** [comment]
@dcorbacho  I don't have a rabbitmq_management_agent section in my config.  Where should i check?

**Comment by michaelklishin** [comment]
If you don't have that section then it's not an issue. `rabbitmqctl environment` outputs the effective config.

**Comment by dcorbacho** [comment]
I tried to reproduce this crash in many different ways, but missing `sample_retention_policies` in the config is not one of them. If that key is missing, the trace is different. Thus, we can discard the idea that there is a race condition loading the configuration of those two applications.

The only way to get that exact trace is if the content of the `detailed` retention policy is an empty list or not-well formed proplist. i.e:
```
 {sample_retention_policies,
   [{global, [{60, 5}, {3600, 60}]},
   {basic, [{60, 20}, {3600, 360}]},
   {detailed, []}]}
]}
```
or
```
 {sample_retention_policies,
   [{global, [{60, 5}, {3600, 60}]},
   {basic, [{60, 20}, {3600, 360}]},
   {detailed, [{10, 5, 2]}]}
]}
```
@laurentluce are you sure you didn't have a typo the first time it happened? It seem you changed the config to make it work. Otherwise, I'm out of ideas on how this can happen.

**Comment by laurentluce** [comment]
@dcorbacho  I also saw the trace once with a detailed empty list.  AFAIK, a detailed empty list worked fine with 3.6.6.

**Comment by dcorbacho** [comment]
@laurentluce All three retention policies are mandatory from 3.6.7, they are required by the metrics collectors, and must contain at least a pair of `{MaxAgeInSeconds, SampleEveryNSeconds}`.

I just made a PR to fail on startup with a more clear error message, and clarified that on the docs.

**Comment by laurentluce** [comment]
@dcorbacho, @michaelklishin   What do you recommend to set detailed to if we don't want retention for that policy?

```
{detailed, [{0, 0}]}
```

**Comment by michaelklishin** [comment]
@laurentluce I'm not sure what you are trying to optimise for but I'd use `{5, 5}` or a similar low value. I don't know if we tried to use zeroes as it doesn't make much sense. The way to control the amount of stats stored has always been the rates mode, which controls how much data is collected.
