### ISSUE TITLE
Metric GC process terminates with badarg in 3.6.9

### ISSUE THREAD

**Issue by laurentluce** [rabbitmq/rabbitmq-management-agent#42]
Management plugin config:

```
{rabbitmq_management,
  [{listener, [{port,     15672},
                {ssl,      false},
                {ssl_opts, [{cacertfile, "/etc/rabbitmq/ssl/cacert.pem"},
                            {certfile,   "/etc/rabbitmq/ssl/server.pem"},
                            {keyfile,    "/etc/rabbitmq/ssl/server.key"}]}]},
   {rates_mode, none},
   {sample_retention_policies,
    [{global,   [{60, 5}]},
     {basic,    [{60, 20}]},
     {detailed, [{10, 5}]}]}
  ]},

```

Log error:

```
=ERROR REPORT==== 30-Mar-2017::00:24:14 ===
** Generic server rabbit_mgmt_gc terminating
** Last message in was start_gc
** When Server state == {state,#Ref<0.0.1.100845>,120000}
** Reason for termination ==
** {badarg,[{erlang,node,[none],[]},
            {rabbit_misc,is_process_alive,1,
                         [{file,"src/rabbit_misc.erl"},{line,872}]},
            {rabbit_mgmt_gc,gc_process,3,
                            [{file,"src/rabbit_mgmt_gc.erl"},{line,136}]},
            {lists,foldl,3,[{file,"lists.erl"},{line,1263}]},
            {ets,do_foldl,4,[{file,"ets.erl"},{line,585}]},
            {ets,foldl,3,[{file,"ets.erl"},{line,574}]},
            {rabbit_mgmt_gc,handle_info,2,
                            [{file,"src/rabbit_mgmt_gc.erl"},{line,44}]},
            {gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,601}]}]}
```

**Comment by michaelklishin** [comment]
The GC process is then restarted, so this can be mostly cosmetic.

**Comment by adfinlay** [comment]
The config file is pretty bare:

```
[
{rabbit,
[
        {vm_memory_high_watermark, 0.65}
]
},
{rabbitmq_web_stomp, [{port, 15674}]}
].

```

When these errors appear, RabbitMQ stops accepting connections and current connections are closed, I assumed that those errors were related as they are the only thing that happens at the time of the issue.

**Comment by dcorbacho** [comment]
This issue seems to be caused by the web STOMP plugin, which I believe @laurentluce is using.
The `none` atom is the initial value of the connection status, generated on the [processor](https://github.com/rabbitmq/rabbitmq-stomp/blob/master/src/rabbit_stomp_processor.erl#L156), which is propagated while emitting stats before the connection is established and/or terminated abruptly.

This condition was already handled by the [STOMP plugin](https://github.com/rabbitmq/rabbitmq-stomp/blob/master/src/rabbit_stomp_reader.erl#L384), but not the web one.

Added a new guard in MQTT too, for 'undefined' and 'none' - although I believe it never takes the value none in MQTT.

**Comment by laurentluce** [comment]
@dcorbacho   Yes, I am using the web STOMP plugin.  Keep in mind that I am seeing this trace at regular intervals.

**Comment by michaelklishin** [comment]
@laurentluce that's expected. The issue has to do with Web STOMP connection stats emission timing on connections that are not yet fully open.

**Comment by laurentluce** [comment]
@michaelklishin  Do you have an ETA for the 3.6.10 release?

**Comment by michaelklishin** [comment]
We can release a milestone next Monday. There are no plans about GA yet as some Pivotal teams haven't shipped 3.6.9 yet.

**Comment by michaelklishin** [comment]
@laurentluce 3.6.10 M1 is [released](https://github.com/rabbitmq/private-docs/blob/master/release_notes/3.6.10.md).

**Comment by michaelklishin** [comment]
Sorry about the private repo release notes link, should point to the public GitHub release now.
