### ISSUE TITLE
Force Event Refresh causes lots of discarded messages

### ISSUE THREAD

**Issue by luos** [rabbitmq/rabbitmq-management-agent#92]
Hi,

When RabbitMQ is slow to start up it may generate lots of discarding messages. 

2020-04-30 05:10:27.244 [error] emulator Discarding message {'$gen_cast',{force_event_refresh,#Ref<0.2714273141.3436707841.245624>}} from <0.344.0> to <0.438.0> in an old incarnation (2) of this node (3)

The cause of these messages is the following: 

https://github.com/rabbitmq/rabbitmq-management-agent/blob/5bc5efdb494e35574f002b967d96f093f08e9ab4/src/rabbit_mgmt_db_handler.erl#L66-L83

Calling into this: 

https://github.com/rabbitmq/rabbitmq-server/blob/d9ac4fba3cf82552da9c8bbedc74cfb9f2cfafda/src/rabbit_amqqueue.erl#L1357-L1363

Basically mnesia still has the old pids inside which causes these messages.

Before restart these were the queues in the system: 

```
[{amqqueue,{resource,<<"/">>,queue,<<"durable-queue">>},
           true,false,none,[],<0.438.0>,[],[],[],undefined,undefined,
           [],[],live,0,[],<<"/">>,
           #{user => <<"guest">>}},
 {amqqueue,{resource,<<"/">>,queue,<<"test_queue">>},
           true,false,none,[],<0.441.0>,[],[],[],undefined,undefined,
           [],[],live,0,[],<<"/">>,
           #{user => <<"my_user">>}}]

```

After restart we get these errors: 

```
2020-04-30 05:10:27.244 [info] <0.344.0> Management plugin: using rates mode 'basic'
2020-04-30 05:10:27.244 [info] <0.344.0> Running boot step recovery defined by app rabbit
2020-04-30 05:10:27.244 [error] emulator Discarding message {'$gen_cast',{force_event_refresh,#Ref<0.2714273141.3436707841.245624>}} from <0.344.0> to <0.438.0> in an old incarnation (2) of this node (3)
2020-04-30 05:10:27.244 [error] emulator Discarding message {'$gen_cast',{force_event_refresh,#Ref<0.2714273141.3436707841.245624>}} from <0.344.0> to <0.441.0> in an old incarnation (2) of this node (3)
```

You can see that if this runs before the queues were properly restarted in a single node installation it may generate as many messages as there are queues. Not sure the reason but in some cases we can even see this in clustered situation, I guess after a full restart. 

This can cause high memory usage, and I think we had in the past when there were multiple thousands of these messages and slow down start of RabbitMQ but now we managed to track this down. 

I am not sure if this is a race condition between management agent starting up and starting of queues, or some other error but it is basically 100% reproducible on a Windows installation with 2 cores, 2 queues, in a VM on my machine. 

I am not sure if there is a way to check if the process id is in the current incarnation, or maybe just check if the pid is alive is enough but it would be good to avoid these messages.
Also I am not sure if it causes any errors that the messages are actually lost in these cases. 

Thanks

**Comment by michaelklishin** [comment]
There is a natural race condition between plugin startup and queue process startup or sync from peers if there are many queues.

I'd need some cold hard data to be convinced that a few messages * by the number of queues would produce a meaningful memory usage footprint. 

Without delaying forced stats refresh until after all queues have recovered *and* elected a master, I'm not sure how this can be avoided. The message is logged [by the runtime](https://github.com/erlang/otp/blob/5624707653ba49b9bb5e6c052d3d7dc4b85e1084/erts/emulator/beam/bif.c#L1961) and not RabbitMQ.

So maybe skipping doing an "event refresh" when the pid is not alive would be the best we can do.

**Comment by luos** [comment]
I think that should be enough, depending if this message is actually not that important.

In the meantime I checked some more logs, and most cases of "Discarding" was not this but the clustering ones, so maybe I mixed up the memory usage with those ones.

This one is maybe just annoying log noise, not really critical.

**Comment by michaelklishin** [comment]
If you want to make event refresh conditional depending on whether queue master pid is alive, please submit a `rabbitmq/rabbitmq-server` PR. The only downside would be a slight (e.g. one stats refresh interval) delay in stats availability for queues but if they are still recovering anyway, that would be hard to even notice.

**Comment by luos** [comment]
Thanks, will do.
