### ISSUE TITLE
Could not find handle.exe, please install from sysinternals" message floods the log

### ISSUE THREAD

**Issue by gulzarahamed** [rabbitmq/rabbitmq-management-agent#97]
I have referred the issue# 90, and it was fixed by increasing the interval time to 10 minutes, and available in version 3.7.24.

but I have installed rabbitmq 3.8.2 and erlang version "Erlang OTP 22 (10.6)",  and I still facing the same issue, I am not deployed handle.exe from sysinternal, is there anyway to limit the log, or I have to do anything in config file.

[rabbit@md1w3yec.log](https://github.com/rabbitmq/rabbitmq-management-agent/files/5354494/rabbit%40md1w3yec.log)

**Comment by lukebakken** [comment]
Please use the latest version of RabbitMQ, which is 3.8.9 available here:

https://github.com/rabbitmq/rabbitmq-server/releases/tag/v3.8.9

Thanks.

**Comment by michaelklishin** [comment]
@gulzarahamed #90 was addressed by https://github.com/rabbitmq/rabbitmq-management-agent/pull/91 in Jan 2020, and `3.8.2` [shipped in Dec 2019](https://www.rabbitmq.com/changelog.html). Please upgrade to the latest release.
